version: '3'
services:
  rails:
    build: .
    command: rails s -b 0.0.0.0
    container_name: atividade
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app 
    depends_on:
      - db
  db:
    image: sqlite3
  
    volumes:
      - atividade_rails_data:/var/lib/sqlite3/data
volumes:
  atividade_rails_data: